export const GetCountryUrl = "/countriesform"
export const GetCityUrl = "/citiesform"
export const GetCustomerUrl = "/customersform"
export const GetItemUrl = "/itemsform"
export const GetDetailUrl = "/detailsform"
export const GetHeadDetailUrl = "/headdetailsform"